site_name: NV9P Amateur Radio
site_description: Ham Radio projects and experiences by NV9P
site_url: http://www.nv9p.com/

theme:
  palette:
    scheme: slate
    primary: deep orange
    accent: deep orange
  icon:
    logo: fontawesome/solid/tower-broadcast
  favicon: img/tower-broadcast-solid.svg
  name: material
  features:
    - navigation.indexes

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Holidays
        - News
      authors_profiles: true
      pagination_per_page: 10
      archive_pagination_per_page: 15
      categories_pagination_per_page: 15
        - meta
  - tags
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

extra:
  social:
    - icon: fontawesome/brands/github
      name: NV9P on Github
      link: https://github.com/caseyjdavis

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic:
  - pymdownx.keys:

nav:
  - Home: index.md
  - About: about.md
  - QSL Cards: qsl-cards.md
  - Logbook: logbook.md
  - Blog:
     - blog/index.md
     - blog/tags.md