site_name: NV9P Amateur Radio
site_description: Ham Radio projects and experiences by NV9P
site_url: http://www.nv9p.com/

theme:
  palette:
    scheme: slate
    primary: deep orange
    accent: deep orange
  icon:
    logo: fontawesome/solid/tower-broadcast
  favicon: img/tower-broadcast-solid.svg
  name: material
  features:
    - navigation.indexes

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
  - blog:
      blog_toc: true
      archive_date_format: yyyy
      pagination_per_page: 12

extra:
  analytics:
    provider: google
    property: G-J9JWWV4FF8
  social:
    - icon: fontawesome/brands/github
      name: NV9P on Github
      link: https://github.com/caseyjdavis

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic:
  - pymdownx.keys:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Blog:
     - blog/index.md
  - Logbook: logbook.md
  - QSL Cards: qsl-cards.md
  - About: about.md